# Q_1

1. Scrape the details of most viewed videos on YouTube from Wikipedia:
Url= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
 You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [1]:
#importing the require libraries
import pandas as pd
import numpy as np
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
#connect to web driver
driver=webdriver.Chrome("chromedriver.exe")
driver

In [3]:
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

#here we have to scrap information from the table.
#initially we will scrap the all the rows excluding headings.
#then we will srap all  the columns .

In [4]:
#web elements for all the rows by Xpath functon
row=1+len(driver.find_elements_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr"))
row

31

In [5]:
Rank=[]
for r in range(1,row):
    try:    #Name
        for n in driver.find_elements_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr["+str(r)+"]/td[1]"):
            Rank.append(n.text)
    except NoSuchElementException:
        Rank.append("-")
Rank

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '28.',
 '29.',
 '30.']

In [6]:
Name=[]
for r in range(1,row):
    try:    #Name
        for n in driver.find_elements_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr["+str(r)+"]/td[2]"):
            Name.append(n.text)
    except NoSuchElementException:
        Name.append("-")
Name

['"Baby Shark Dance"[22]',
 '"Despacito"[24]',
 '"Johny Johny Yes Papa"[25]',
 '"Shape of You"[26]',
 '"See You Again"[27]',
 '"Masha and the Bear – Recipe for Disaster"[30]',
 '"Uptown Funk"[31]',
 '"Bath Song"[32]',
 '"Learning Colors – Colorful Eggs on a Farm"[33]',
 '"Gangnam Style"[34]',
 '"Phonics Song with Two Words"[36]',
 '"Sugar"[37]',
 '"Sorry"[38]',
 '"Dame Tu Cosita"[39]',
 '"Roar"[40]',
 '"Counting Stars"[41]',
 '"Thinking Out Loud"[42]',
 '"Dark Horse"[43]',
 '"Wheels on the Bus"[44]',
 '"Faded"[45]',
 '"Shake It Off"[46]',
 '"Lean On"[47]',
 '"Girls Like You"[48]',
 '"Bailando"[49]',
 '"Let Her Go"[50]',
 '"Mi Gente"[51]',
 '"Perfect"[52]',
 '"Waka Waka (This Time for Africa)"[53]',
 '"Hello"[54]',
 '"Axel F"[55]']

In [7]:
Artist=[]
for r in range(1,row):
    try:    #Artist
        for n in driver.find_elements_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr["+str(r)+"]/td[3]"):
            Artist.append(n.text)
    except NoSuchElementException:
        Artist.append("-")
Artist

["Pinkfong Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Ed Sheeran',
 'Wiz Khalifa',
 'Get Movies',
 'Mark Ronson',
 'Cocomelon – Nursery Rhymes',
 'Miroshka TV',
 'Psy',
 'ChuChu TV',
 'Maroon 5',
 'Justin Bieber',
 'El Chombo',
 'Katy Perry',
 'OneRepublic',
 'Ed Sheeran',
 'Katy Perry',
 'Cocomelon – Nursery Rhymes',
 'Alan Walker',
 'Taylor Swift',
 'Major Lazer',
 'Maroon 5',
 'Enrique Iglesias',
 'Passenger',
 'J Balvin',
 'Ed Sheeran',
 'Shakira',
 'Adele',
 'Crazy Frog']

In [8]:
Upload_date=[]
for r in range(1,row):
    try:    #Upload_date
        for n in driver.find_elements_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr["+str(r)+"]/td[5]"):
            Upload_date.append(n.text)
    except NoSuchElementException:
         Upload_date.append("-")
Upload_date

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'January 30, 2017',
 'April 6, 2015',
 'January 31, 2012',
 'November 19, 2014',
 'May 2, 2018',
 'February 27, 2018',
 'July 15, 2012',
 'March 6, 2014',
 'January 14, 2015',
 'October 22, 2015',
 'April 5, 2018',
 'September 5, 2013',
 'May 31, 2013',
 'October 7, 2014',
 'February 20, 2014',
 'May 24, 2018',
 'December 3, 2015',
 'August 18, 2014',
 'March 22, 2015',
 'May 31, 2018',
 'April 11, 2014',
 'July 25, 2012',
 'June 29, 2017',
 'November 9, 2017',
 'June 4, 2010',
 'October 22, 2015',
 'June 16, 2009']

In [9]:
Views=[]
for r in range(1,row):
    try:    #Views_
        for n in driver.find_elements_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr["+str(r)+"]/td[4]"):
            Views.append(n.text)
    except NoSuchElementException:
        Views.append("-")
        
Views

['8.81',
 '7.40',
 '5.47',
 '5.35',
 '5.14',
 '4.44',
 '4.20',
 '4.16',
 '4.16',
 '4.09',
 '3.93',
 '3.49',
 '3.44',
 '3.39',
 '3.37',
 '3.32',
 '3.27',
 '3.09',
 '3.08',
 '3.08',
 '3.07',
 '3.05',
 '3.05',
 '3.05',
 '3.01',
 '2.93',
 '2.87',
 '2.85',
 '2.85',
 '2.84']

In [10]:
df=pd.DataFrame({})
df['Rank']=Rank
df['Name']=Name
df['Artist']=Artist
df['Upload date']=Upload_date
df['Views']=Views
df

,Rank,Name,Artist,Upload date,Views
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,"June 17, 2016",8.81
1,2.,"""Despacito""[24]",Luis Fonsi,"January 12, 2017",7.40
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,"October 8, 2016",5.47
3,4.,"""Shape of You""[26]",Ed Sheeran,"January 30, 2017",5.35
4,5.,"""See You Again""[27]",Wiz Khalifa,"April 6, 2015",5.14
5,6.,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,"January 31, 2012",4.44
6,7.,"""Uptown Funk""[31]",Mark Ronson,"November 19, 2014",4.20
7,8.,"""Bath Song""[32]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.16
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[33]",Miroshka TV,"February 27, 2018",4.16
9,10.,"""Gangnam Style""[34]",Psy,"July 15, 2012",4.09
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,"March 6, 2014",3.93
11,12.,"""Sugar""[37]",Maroon 5,"January 14, 2015",3.49
12,13.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.44
13,14.,"""Dame Tu Cosita""[39]",El Chombo,"April 5, 2018",3.39
14,15.,"""Roar""[40]",Katy Perry,"September 5, 2013",3.37
15,16.,"""Counting Stars""[41]",OneRepublic,"May 31, 2013",3.32
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,"October 7, 2014",3.27
17,18.,"""Dark Horse""[43]",Katy Perry,"February 20, 2014",3.09
18,19.,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.08
19,20.,"""Faded""[45]",Alan Walker,"December 3, 2015",3.08
20,21.,"""Shake It Off""[46]",Taylor Swift,"August 18, 2014",3.07
21,22.,"""Lean On""[47]",Major Lazer,"March 22, 2015",3.05
22,23.,"""Girls Like You""[48]",Maroon 5,"May 31, 2018",3.05
23,24.,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.05
24,25.,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.01
25,26.,"""Mi Gente""[51]",J Balvin,"June 29, 2017",2.93
26,27.,"""Perfect""[52]",Ed Sheeran,"November 9, 2017",2.87
27,28.,"""Waka Waka (This Time for Africa)""[53]",Shakira,"June 4, 2010",2.85
28,29.,"""Hello""[54]",Adele,"October 22, 2015",2.85
29,30.,"""Axel F""[55]",Crazy Frog,"June 16, 2009",2.84

# Question_2

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [11]:
url='https://www.bcci.tv/international/fixtures'
driver.get(url)

In [12]:
Match_title=[]
Series=[]
Place=[]
Date=[] 
Time=[]

In [13]:
#match_title
try:
    for t in  driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__format']"):
        Match_title.append(t.text)
except NoSuchElementException:
    Match_title.append("-")

In [14]:
#Series
try:
    for s in driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
        Series.append(s.text)
except NoSuchElementException:
    Series.append("_")

In [15]:
#place
try:
    for p in driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span"):
        Place.append(p.text)
except NoSuchElementException:
    Place.append("_")

In [16]:
#Date
try:
    for d in driver.find_elements_by_xpath("//span[@class='fixture__datetime tablet-only']//strong"):
        Date.append(d.text)
except NoSuchElementException:
    Date.append("_")
    
except StaleElementReferenceException:#handling Stale element exception
    Date.append("_")
Date

['', '', '', '', '', '', '', '', '', '', '', '']

In [17]:
df=pd.DataFrame({})
df['Match_title']=Match_title
df['Series']=Series
df['Place']=Place
df['Date']= Date

df

   Match_title                       Series                         Place Date
0         TEST  ICC WORLD TEST CHAMPIONSHIP   The Ageas Bowl, Southampton
1          ODI       SRI LANKA V INDIA 2021  R Premadasa Stadium, Colombo
2          ODI       SRI LANKA V INDIA 2021  R Premadasa Stadium, Colombo
3          ODI       SRI LANKA V INDIA 2021  R Premadasa Stadium, Colombo
4         T20I       SRI LANKA V INDIA 2021  R Premadasa Stadium, Colombo
5         T20I       SRI LANKA V INDIA 2021  R Premadasa Stadium, Colombo
6         T20I       SRI LANKA V INDIA 2021  R Premadasa Stadium, Colombo
7         TEST         ENGLAND V INDIA 2021      Trent Bridge, Nottingham
8         TEST         ENGLAND V INDIA 2021                Lord's, London
9         TEST         ENGLAND V INDIA 2021             Headingley, Leeds
10        TEST         ENGLAND V INDIA 2021              The Oval, London
11        TEST         ENGLAND V INDIA 2021      Old Trafford, Manchester

# Question-3

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [18]:
url='https://www.guru99.com/'
driver.get(url)

In [19]:
#click on slelenium
driver.find_element_by_xpath("/html/body/div[2]/section[4]/div/div/div/div/div/div/div/div[1]/div/ul[1]/li[3]").click()

In [20]:
#select and click selenium exception handling
driver.find_element_by_xpath('/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]/a').click()

In [21]:
rows=1+len(driver.find_elements_by_xpath('/html/body/div[2]/section[3]/div/div[1]/main/div[1]/div/div/div/div/div/div[2]/table/tbody/tr'))
rows

88

In [22]:
Exception_names=[]
for r in range(2,rows):
    for c in driver.find_elements_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div[1]/div/div/div/div/div/div[2]/table/tbody/tr["+str(r)+"]/td[1]"):
        Exception_names.append(c.text)

In [23]:
Exception_names

[]

In [24]:
Description=[]
for r in range(2,rows):
    for c in driver.find_elements_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div[1]/div/div/div/div/div/div[2]/table/tbody/tr["+str(r)+"]/td[2]"):
        Description.append(c.text)

In [25]:
Description

[]

In [26]:
df=pd.DataFrame({})
df['Name']=Exception_names
df['Description']=Description
df

Empty DataFrame
Columns: [Name, Description]
Index: []

# Q_4

Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code

# Q_5

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [27]:
url="https://github.com/explore"
driver.get(url)

In [28]:
#click on trending
driver.find_element_by_xpath('/html/body/div[4]/main/div[1]/nav/div/a[3]').click()

In [29]:
#Reprository Title
Repository_title=[]
for i in driver.find_elements_by_xpath("//h1[@class='Repository title']"):
    Repository_title.append(i.text)

In [30]:
Url=[]
for u in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']//a"):
    Url.append(u.get_attribute('href'))
    
Url

['https://github.com/programthink/zhao',
 'https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation',
 'https://github.com/CaffeineMC/sodium-fabric',
 'https://github.com/n8n-io/n8n',
 'https://github.com/facebookresearch/AugLy',
 'https://github.com/vxunderground/MalwareSourceCode',
 'https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard',
 'https://github.com/EssayKillerBrain/EssayKiller_V2',
 'https://github.com/organicmaps/organicmaps',
 'https://github.com/rustdesk/rustdesk',
 'https://github.com/algorithm-visualizer/algorithm-visualizer',
 'https://github.com/academic/awesome-datascience',
 'https://github.com/megaease/easegress',
 'https://github.com/TheBobPony/getwindows11.tech',
 'https://github.com/donnemartin/system-design-primer',
 'https://github.com/kwai/DouZero',
 'https://github.com/programthink/opensource',
 'https://github.com/facebookresearch/xcit',
 'https://github.com/githubdev03/RDP',
 'https://github.com/tailwindlabs/tailwindcss',
 'https://github.com/coqui-ai/TTS',
 'https://github.com/v2fly/v2ray-core',
 'https://github.com/nothings/stb',
 'https://github.com/mltframework/shotcut',
 'https://github.com/flutter/flutter']

In [31]:
#clicking on ist 
driver.find_element_by_xpath('/html/body/div[4]/main/div[3]/div/div[2]/article[1]/h1/a').click()

In [32]:
Repository_title=[] 
Repository_description=[]
Contributors_count=[]
Language_used=[]

In [33]:
for i in Url:
    driver.get(i)
    
    try:   #Repository_title=[]
        i= driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']//a")
        Repository_title.append(i.text)
    except NoSuchElementException:
        Repository_title.append("-")

In [34]:
for i in Url:
    driver.get(i)
    
    try: #Repository_description=[]
        r= driver.find_element_by_xpath("//div[@class='Box-body px-5 pb-5']")
        Repository_description.append(r.text)
            
    except NoSuchElementException:
            Repository_description.append('-')

In [35]:
for i in Url:
    driver.get(i)
    
    try:
        c= driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[4]/div/h2/a/span")
        Contributors_count.append(c.text)
            
    except NoSuchElementException:
         Contributors_count.append("-")

In [36]:
 Language_used=[]
for l in Url:
    driver.get(l)
    
    try:
        l= driver.find_element_by_xpath('/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[3]/div/ul')
        Language_used.append(l.text)  
            
    except NoSuchElementException:
        Language_used.append("-")

In [37]:
df=pd.DataFrame({})
df['Repository_title']=Repository_title
df['Repository_description']=Repository_description
df['Contributors_count']=Contributors_count
df['Language_used']=Language_used
df

,Repository_title,Repository_description,Contributors_count,Language_used
0,zhao,Table of Contents\n俺整理的《太子党关系网络》\n简介\n下载说明\n多人...,2,-
1,The-Complete-FAANG-Preparation,Welcome to The-Complete-FAANG-Preparation Disc...,22,-
2,sodium-fabric,Sodium (for Fabric)\nSodium is a free and open...,-,
3,n8n,n8n - Workflow Automation Tool\nn8n is an exte...,14,-
4,AugLy,AugLy is a data augmentations library that cur...,1,-
5,MalwareSourceCode,managed by vx-underground | follow us on Twitt...,-,Assembly\n92.1%\nC\n1.9%\nBrainfuck\n1.5%\nRof...
6,Flutter-Responsive-Admin-Panel-or-Dashboard,Responsive Admin Panel or Dashboard - Flutter ...,4,-
7,EssayKiller_V2,EssayKiller\n通用型议论文创作人工智能框架，仅限交流与科普。\nBilibili...,-,-
8,organicmaps,Organic Maps\nOrganic Maps is a better fork of...,-,
9,rustdesk,RustDesk | Your Remote Desktop Software\nServe...,,ko-fi.com/rustdesk
10,algorithm-visualizer,Algorithm Visualizer\nAlgorithm Visualizer is ...,,https://www.paypal.com/cgi-bin/webscr?cmd=_don...
11,awesome-datascience,AWESOME DATA SCIENCE\nAn open source Data Scie...,,
12,easegress,Easegress\nEasegress\nWhat is Easegress\nFeatu...,-,-
13,getwindows11.tech,Get Windows 11\nThis is the website for Get Wi...,-,HTML\n93.2%\nJavaScript\n4.2%\nRuby\n2.6%
14,system-design-primer,English ∙ 日本語 ∙ 简体中文 ∙ 繁體中文 | العَرَبِيَّة ∙ ব...,110,-
15,DouZero,[ICML 2021] DouZero: Mastering DouDizhu with S...,-,-
16,opensource,俺收藏的开源项目\n开源库及示例代码\n本目录放置：面向程序员的开源代码库清单（含示例代码）...,-,-
17,xcit,Cross-Covariance Image Transformer (XCiT)\nPyT...,-,-
18,RDP,Windows2019RDP-US\nCreate a free VPS with 2cpu...,4,-
19,tailwindcss,A utility-first CSS framework for rapidly buil...,229k,-
20,TTS,🐸TTS is a library for advanced Text-to-Speech ...,-,
21,v2ray-core,Project V\nProject V is a set of network tools...,-,
22,stb,stb\nsingle-file public domain (or MIT license...,-,-
23,shotcut,"Shotcut - a free, open source, cross-platform ...",42,-
24,flutter,Flutter is Google's SDK for crafting beautiful...,-,Dart\n99.2%\nObjective-C\n0.2%\nJava\n0.2%\nC+...

# Q-6

6. Scrape the details of top 100 songs on billiboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [38]:
#connect to web driver
driver=webdriver.Chrome("chromedriver.exe")
driver

In [39]:
url="https://www.billboard.com/charts"
driver.get(url)

In [40]:
#click on the view chart option
driver.find_element_by_xpath("/html/body/main/div[2]/div/div[1]/a/div[2]/div[2]/div[1]").click()

In [41]:
Song_name=[]
Artist_name=[]
Last_week_rank=[]
Peak_rank=[]
Weeks_on_board=[]

In [42]:
#Song_name=[]
try:
    for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']"):
        Song_name.append(i.text)
    
except NoSuchElementException:
    Song_name.append("_")

In [43]:
#Artist_name=[]
try:
    for a in driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']"):
        Artist_name.append(a.text)
    
except NoSuchElementException:
    Artist_name.append("_")

In [44]:
#Last_week_rank=[]
try:
    for r in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']"):
        Last_week_rank.append(r.text)

except NoSuchElementException:
    Last_week_rank.append("-")

In [45]:
#Peak_rank=[]
try:
    for p in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']"):
        Peak_rank.append(p.text)
except NoSuchElementException:  
    Peak_rank.append("-")

In [46]:
#Weeks_on_board=[]
try:
    for w in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']"):
        Weeks_on_board.append(w.text)
except NoSuchElementException:
    Weeks_on_board.append("-")

In [47]:
df=pd.DataFrame({})
df['Song_name']=Song_name
df['Artist_name']=Artist_name
df['Last_week_rank']=Last_week_rank
df['Peak_rank']=Peak_rank
df['Weeks_on_board']=Weeks_on_board

In [48]:
df

,Song_name,Artist_name,Last_week_rank,Peak_rank,Weeks_on_board
0,Butter,BTS,1,1,3
1,Good 4 U,Olivia Rodrigo,2,1,4
2,Levitating,Dua Lipa Featuring DaBaby,3,2,36
3,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,6,1,12
4,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),4,1,14
...,...,...,...,...,...
95,Things A Man Oughta Know,Lainey Wilson,93,93,4
96,Country Again,Thomas Rhett,89,73,6
97,Drunk (And I Don't Wanna Go Home),Elle King & Miranda Lambert,92,79,7
98,If You Want To,Lil Baby & Lil Durk,-,99,1
99,Seeing Green,"Nicki Minaj, Drake & Lil Wayne",67,12,4

# Q_7

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and 
click on search. All this should be done through code

# Q_8

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [49]:
url=' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/'

In [50]:
driver.get(url)

In [51]:
Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

In [52]:
#row
row=1+len(driver.find_elements_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr'))

In [53]:
row

101

In [54]:
for r in range(1,row):
    try:    #Book_name=[]
        
        for b in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr["+str(r)+"]/td[2]"):
            Book_name.append(b.text)
            
    except NoSuchElementException:
        Book_name.append("-")
        
    
    try:    #Author_name=[]
        
        for a in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr["+str(r)+"]/td[3]"):
            Author_name.append(a.text)
            
    except NoSuchElementException:
        Author_name.append("-")
        
        
     
    try:    #Volumes_sold=[]
        
        for v in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr["+str(r)+"]/td[4]"):
            Volumes_sold.append(v.text)
            
    except NoSuchElementException:
        Volumes_sold.append("-")
            
            
    try:    #Publisher=[]
        
        for p in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr["+str(r)+"]/td[5]"):
            Publisher.append(p.text)
            
    except NoSuchElementException:
        Publisher.append("-")     
        
        
        
    try:    #Genre=[]
        
        for g in driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr["+str(r)+"]/td[4]"):
            Genre.append(g.text)
            
    except NoSuchElementException:
         Genre.append("-")

In [55]:
df=pd.DataFrame({})
df['Book_name']=Book_name
df['Author_name']=Author_name
df['Volumes_sold']=Volumes_sold
df['Publisher']=Publisher
df['Genre']=Genre
df

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"5,094,805"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,"4,475,152"
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,"4,200,654"
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,"4,179,479"
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,"3,758,936"
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,"807,311"
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,"794,201"
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,"792,187"
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,"791,507"
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,"791,095"

# Q_9

9. Scrape the details most watched tv series of all time from imdb.com.
 Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [76]:
url='https://www.imdb.com/list/ls095964455/ '
driver.get(url)

In [77]:
Name=[]
Year_span=[]
Genre=[]
Run_time=[]

In [78]:
url=[]
for i in driver.find_elements_by_xpath("//div[@class='lister-item-image ribbonize']//a"):
    url.append(i.get_attribute('href'))

In [79]:
len(url)

100

In [80]:
name=[]

In [81]:
for r in range (1,101):
    try:
        n=driver.find_element_by_xpath("/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div["+str(r)+"]/div[2]/h3/a")
        name.append(n.text)  
    except NoSuchElementException:
         name.append("-")

In [82]:
#Year_span
Year_span=[] 
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

In [83]:
#Genre
Genre=[]
for g in driver.find_elements_by_class_name("genre"):
    Genre.append(g.text)

In [84]:
#Run_time=[]
Run_time=[]
for r in driver.find_elements_by_class_name("runtime"):
    Run_time.append(r.text)

In [85]:
driver.find_element_by_xpath("/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[1]/div[2]/h3/a").click()

In [86]:
Ratings=[]
Votes=[]

In [87]:
for i in url:
    driver.get(i)
    
    try: #Ratings=[]
        r=driver.find_element_by_xpath("/html/body/div[4]/div/div[2]/div[5]/div[1]/div[2]/div/div[1]/div[2]/div/div[1]/div[1]/div[1]/strong/span")
        Ratings.append(r.text)
        
    except NoSuchElementException:
        Ratings.append("_")
         
    try: #Votes=[]
        v=driver.find_element_by_xpath("/html/body/div[4]/div/div[2]/div[5]/div[1]/div[2]/div/div[1]/div[2]/div/div[1]/div[1]/a/span")
        Votes.append(v.text)
        
    except NoSuchElementException:
        Votes.append("_")

In [88]:
df=pd.DataFrame({})
df['Name']=name
df['Year span']=Year_span
df['Genre']=Genre
df['Run time']=Run_time
df['Ratings']= Ratings
df['Votes']=Votes
df

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,_,_
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,_,_
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,_,_
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,_,_
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,_,_
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,_,_
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,_,_
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,_,_
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,_,_
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,_,_

# Q10

10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code

In [69]:
url='https://archive.ics.uci.edu/'

In [70]:
driver.get(url)

In [71]:
#click on view all data set
driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b").click()

In [72]:
#all the row of the table
row=(1+len(driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr")))
row

590

In [73]:
Dataset_name=[]
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attribute=[]
Year=[]

In [74]:
for r in range(2,row):
    try:#Dataset_name
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[1]")
        Dataset_name.append(n.text)
        
    except NoSuchElementException:
        Dataset_name.append("-")
        
        
    try:#Data_type=[]
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[2]")
        Data_type.append(n.text)
        
    except NoSuchElementException:
        Data_type.append("-")
       
    try:#Task=[]
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[3]")
        Task.append(n.text)
        
    except NoSuchElementException:
        Task.append("-")
        
    try:#Attribute_type=[]
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[4]")
        Attribute_type.append(n.text)
        
    except NoSuchElementException:
        Attribute_type.append("-")
        
        
    try:#No_of_instances=[]
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[5]")
        No_of_instances.append(n.text)
        
    except NoSuchElementException:
        No_of_instances.append("-")
        
        
    try:#No_of_attribute=[]
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[6]")
        No_of_attribute.append(n.text)
        
    except NoSuchElementException:
        No_of_attribute.append("-")
        
        
    try:#Year=[]
        n=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr["+str(r)+"]/td[7]")
        Year.append(n.text)
        
    except NoSuchElementException:
        Year.append("-")

In [75]:
df=pd.DataFrame({})
df['Dataset name']=Dataset_name
df['Data type']=Data_type
df['Task']=Task
df['Attribute type']=Attribute_type
df['No of instances']=No_of_instances
df['No of attribute']=No_of_attribute
df['Year']=Year
df

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021